create first working version of the GPT2 embedding comparison
NASA-PDS/llms-and-pds pull request #10
Opened 2023-08-02 15:44 UTC by tloubrieu-jpl

## 🗒️ Summary

Make an initial version to compare embeeding with GPT2

2023-08-02 15:50 UTC, nutjob4life requested changes
Looks like some code linting issues … maybe the pre-commit hook didn't run? 🤔

2023-08-02 15:50 UTC, nutjob4life commented on src/pds/llm/GPT2.py
> +    vectors = []
Docstring missing for this function; did `flake8` linting run for this commit?

2023-08-02 17:19 UTC, tloubrieu-jpl commented on src/pds/llm/GPT2.py
> +
thanks @nutjob4life , I'm doing that

2023-08-02 18:03 UTC, nutjob4life commented
> Next time, we would need to run `tox -e lint` to detect the style errors that we are committing to this repository, there are still plenty of them.

Also the pre-commit hooks should take care of that automatically. It's possible these commands didn't get run initially?
```
    pre-commit install
    pre-commit install -t pre-push
    pre-commit install -t prepare-commit-msg
    pre-commit install -t commit-msg
```

2023-10-13 21:31 UTC, tloubrieu-jpl commented
Has been manually merged.

2023-10-13 21:31 UTC, closed without merging